#!/bin/bash

ln -s $(realpath bashrc) ~/.bashrc
ln -s $(realpath gitconfig) ~/.gitconfig

ln -s $(realpath scripts/dwm_autostart) ~/.dwm_autostart

mkdir -p ~/.config
ln -s $(realpath compton.conf) ~/.config/compton.conf
ln -s $(realpath redshift.conf) ~/.config/redshift.conf

mkdir -p ~/.config/nvim
ln -s $(realpath vimrc) ~/.config/nvim/init.vim
