#!/bin/sh
#   ▗   ▗
# ▛▘▜▘▀▌▜▘▌▌▛▘
# ▄▌▐▖█▌▐▖▙▌▄▌ - Display status in one line, to be embedded on statuslines.
# ==============================================================================

# Thank to xero's script sysinfo
#	http://git.io/v4aH5

# Thank to z3bra's mkbar translated now in C
#	http://git.z3bra.org/mkb/files.html

# More edits by Sasa Savic
#   https://github.com/saleone

FULL=${FULL-█}
EMPTY=${EMPTY-░}
SIZE=${SIZE-10}

draw()
{
	perc=$1
	size=$2

	inc=$(( perc * size / 100 ))

	for v in $(seq 0 $(( size - 1 )))
	do
		[ "$v" -le "$inc" ] \
			&& out="${out}${FULL}" \
			|| out="${out}${EMPTY}"
	done

	printf '%s' "$out"
}

cpu()
{
	cpu="$(grep 'cpu ' /proc/stat |\
		awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage}')"
	cpu=$(printf "%.0f" $cpu)

	printf 'cpu %s' "$(draw $cpu $SIZE)"
}

ram()
{
	ram="$(free | awk '/Mem:/ {print int($3/$2 * 100.0)}')"

	printf "ram %s" "$(draw $ram $SIZE)"
}

battery()
{
    battery=/sys/class/power_supply/BAT1
    b_full=$battery/energy_full
    b_now=$battery/energy_now
    bf=`cat $b_full`
    bn=`cat $b_now`
    charge=`printf $(( 100 * $bn / $bf ))`
    printf "bat %s" "$(draw $charge $SIZE)"
}
while :
do
    printf ' %s  %s  %s  %s  \n' \
        "$(cpu)" "$(ram)" "$(battery)" "$(date +"%d.%m.%Y  %R")"
    sleep 1
done
