#! /bin/sh
setxkbmap -option caps:ctrl_modifier -layout "us,ba,rs" -option "grp:alt_shift_toggle" &
compton --opengl --vsync opengl-swc --paint-on-overlay -b &
feh --bg-scale ~/.wallpaper.jpg &
redshift &
polybar default &
sxhkd &

bspc monitor -d 1 2 3 4 5 0

bspc config border_width             3
bspc config window_gap               10

bspc config split_ratio              0.50
bspc config borderless_monocle       true
bspc config gapless_monocle          true

# base00
bspc config normal_border_color      "#ffffff"

# base0b
bspc config active_border_color      "#198844"

# base09
bspc config focused_border_color     "#f96a38"

# base01
bspc config presel_feedback_color    "#e0e0e0"
