" Globals that need to activate
" Install plugins with 'junegunn/vim-plug'
if empty(glob('~/.config/nvim/autoload/plug.vim'))
  silent !curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin("~/.config/nvim/plugged")
Plug 'tpope/vim-sensible'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'chriskempson/base16-vim'
call plug#end()

" ======================
"  VIM BUILDIN SETTINGS
" ======================

" Regular copy and paste
set pastetoggle=<F2>
set clipboard=unnamedplus

" Remove trailing whitespace on save
autocmd BufWritePre * %s/\s\+$//e

" Mouse support
set mouse=a

" Enable line numbers
set number
set relativenumber

" Theme
colorscheme base16-google-light

" No background
hi Normal guibg=NONE ctermbg=NONE

" =================
"  PLUGIN SETTINGS
" =================

" CtrlP
" -----
let g:ctrlp_working_path_mode = 'w'
let g:ctrlp_root_markers = ['*.code-workspace']
let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files -co --exclude-standard']

