#!/bin/sh

# Install all the dependencies
sudo apt install --fix-broken-install
sudo apt install \
	build-essential \
	bash-completion \
	curl \
	wget \
	libnotify-bin \
	dunst \
	firefox-esr \
	tmux \
	feh \
	compton \
	redshift \
	git \
	neovim \
	brightnessctl \
	fish \
	bspwm \
	rofi \
	i3lock \
	mpv \
	fonts-ubuntu* \
	fonts-firacode \
	fonts-liberation \
	fonts-font-awesome
sudo apt install --fix-broken-install

# Clone configs
cd ~
git init
git remote add origin https://github.com/saleone/configs
git fetch
git checkout -f origin/master

# Install VSCode
wget https://go.microsoft.com/fwlink/?LinkID=760868 -O code.deb
sudo dpkg -i code.deb
sudo apt install -f -y
rm code.deb

