#!/bin/bash
# TODO: Normalize brightness to curr = (curr % (max / 10)) * (max/10) to force 10% increases.
# TODO: Add notification on change as perc($(dirname path)/max_brightness)

path=/sys/class/backlight/intel_backlight/brightness
cur_val=$(cat $path)
max_val=$(cat /sys/class/backlight/intel_backlight/max_brightness)

if [[ "$1" == "get" ]]
then
	echo "$cur_val / $max_val"
	exit 0;
fi

if [[ "$1" == "set" ]]
then

	if [ "$max_val" -lt "$2" ]; then
		echo $max_val > $path;
	else
		echo $2 > $path;
	fi
	exit 0;
fi

change=750

if [[ "$1" == "dec" ]]
then
	change=-750
fi

new_val=$(( cur_val + change ))

if [ "$max_val" -lt "$new_val" ]; then
	new_val=$max_val
fi

echo $new_val > $path

