#!/bin/sh
BASEDIR=$(dirname $(realpath $0))

unknown_target() {
	echo "Unknown $1 target '$2'. Use: "
	shift 2
	for var in "$@"; do
		echo "\t$var"
	done
}

case "$1" in
"notify")
	case "$2" in
	"status")
		notify-send " $($BASEDIR/status_notification) "
		exit 0
		;;
	*)
		unknown_target $@ status
		;;
	esac
	;;
"wm")
	case "$2" in
	"exit")
		pkill dwm
		exit 0
		;;
	*)
		unknown_target $@ exit
		;;
	esac
	;;
"power")
	case "$2" in
	"shutdown")
		systemctl poweroff
		exit 0
		;;
	"sleep")
		slock &
		systemctl suspend
		exit 0
		;;
	"restart")
		systemctl reboot
		exit 0
		;;
	*)
		unknown_target $@ shutdown sleep restart
		;;
	esac
	;;
*)
	echo "Unknown command '$1'. Use:\n\tnotify\n\tpower\n\twm"
	exit 1
	;;
esac
