#!/bin/bash
compton --opengl --vsync opengl-swc --paint-on-overlay -b &
feh --bg-scale ~/.wallpaper.jpg &
dwm_status &
setxkbmap -option caps:ctrl_modifier &
setxkbmap -layout "us,ba,rs" -option "grp:alt_shift_toggle" &
redshift &
