#!/bin/sh

cpu()
{
    cpu=$(top -bn1 | grep %Cpu | awk '{value=$2} END {print value}')

    # When CPU reaches 100% load, command above return "us,"
    if [ $cpu = 'us,' ]; then
        cpu='100,0'
    fi

    cpu=$(printf "%.0f" $cpu)

    printf ' %02d%%' $cpu
}

ram()
{
    printf " $(free -h | awk '/Mem/ {printf "%sB", $3}')"
}

battery()
{
    max_charge=1
    now_charge=0

    for dir in /sys/class/power_supply/BAT*/;
    do
        # Different latops, different files:
        if [ -f $dir"charge_full" ]; then
            # Dell Latitude 5480 (single bat)
            max_charge=$(($max_charge + `cat $dir"charge_full"`))
            now_charge=$(($now_charge + `cat $dir"charge_now"`))
        elif [ -f $dir"energy_full" ]; then
            # Lenovo Thinkpad T580 (dual bats)
            max_charge=$(($max_charge + `cat $dir"energy_full"`))
            now_charge=$(($now_charge + `cat $dir"energy_now"`))
        fi
    done

    if [ $now_charge -gt 0 ]; then
        status=" "
        if [ "$(cat /sys/class/power_supply/AC/online)" -eq '1' ]; then
            status=""
        fi

        charge_perc=$((100 * now_charge / max_charge))
        icon=" "
        if [ $charge_perc -le 90 ]; then
            icon=" "
        fi

        if [ $charge_perc -le 75 ]; then
            icon=" "
        fi

        if [ $charge_perc -le 25 ]; then
            # Send battery low notification (once!)
            icon=" "
        fi

        if [ $charge_perc -le 10 ]; then
            # Send battery critical notification (once!)
            icon=" "
        fi

        printf "%s%s%s%%" "$status" "$icon" "$charge_perc"
    fi


}

current_brightness()
{
    value=$(( $(brightnessctl g) * 100 / $(brightnessctl m) ))
    if [ $value -ge 100 ]; then
        printf ' max';
    else
        printf ' %02d%%' "$value";
    fi
}

current_datetime()
{
    printf ' %s' "$(date +"%b %d, %R")"
}

current_time()
{
    printf ' %s' "$(date +"%R")"
}

current_volume()
{
    # TODO: Set mute icon
    # val=$(pactl list sink | grep "Mute:") ...
    icon=" "
    vol=$(pactl list sinks | grep "Volume:" | grep -Eo "[0-9]+\%" | grep -Eo "[0-9]+" | head -1)

    if [ $vol -le 60 ]; then
        icon=" "
    fi

    if [ $vol -eq 0 ]; then
        icon=" "
    fi

    printf '%s%s%%' "$icon" "$vol"
}
