#!/bin/sh
BASEDIR=$(dirname `realpath $0`)

. "$BASEDIR/status_lib"

while true
do
	statusline="$(cpu)  $(current_volume)  $(battery)  $(current_time)"
	echo "$statusline"
	xsetroot -name "  $statusline  "
	sleep "0.5"
done
