# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

##
# Aliases
alias v="vim"
alias mkdir="mkdir -pv" # make parent directories when creating subdirectory
alias listen="lsof -P -g -n" # list apps connected to network
alias ls="ls --color=auto --classify" # more descriptive list
alias rm="rm -i" # ask when deleting something
alias vim="gvim -v" # use terminal version with +clipboard support

##
# Ubuntu:
# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

##
# Global variables
EDITOR="vim"; export EDITOR;
PS1="\u@\h in \w \nexec \$ "

##
# My changes
if [ ! -d ~/.my_bin/ ]; then mkdir ~/.my_bin; fi # create my bin folder
export PATH=~/.my_bin:$PATH # add my bin folder to PATH


