# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

##
# Aliases
alias mkdir="mkdir -pv" # make parent directories when creating subdirectory
alias listen="lsof -P -g -n" # list apps connected to network
alias ls="ls --color=auto --classify" # more descriptive list
alias rm="rm -i" # ask when deleting something
alias h="history" # easily check command history

# Git aliases
alias gits="git status"
alias gitc="git commit"
alias gita="git add"
alias gitl="git log"
alias gitlo="git log --pretty=oneline"
alias gitd="git diff"
alias gitp="git push"
alias gitpl="git pull"

# Mercurial aliases
alias hgs="hg status"
alias hgc="hg commit"
alias hga="hg add"
alias hgl="hg log --style compact"
alias hgd="hg diff"
alias hgp="hg push"
alias hgpl="hg pull"
alias hgpwb="hg bookmarks | grep '*'"


# Directory traversing aliases
alias dirs="dirs -v" # show directories with dirs

##
# Global variables
EDITOR="vim"; export EDITOR;

PS1="\[\033[01;39m\] \W \[\033[0m\]➤ "

export VAGRANT_DEFAULT_PROVIDER=virtualbox

##
# My changes
source /etc/bash_completion

# Add users local binary folder
if [ ! -d $HOME/.local/bin ]; then mkdir $HOME/.local/bin; fi
export PATH=$HOME/.local/bin:$PATH

# If there is rust cargo bin folder add it to PATH
if [ -d $HOME/.cargo/bin ]; then
    export PATH="$HOME/.cargo/bin:$PATH"
fi

export RUST_REPO=$HOME/.cargo/rust_src
# Define rust sources path
if [ ! -d $RUST_REPO ]; then
    mkdir -p $RUST_REPO
fi
export RUST_SRC_PATH="$RUST_REPO/src"

# Remap caps lock to control
setxkbmap -option caps:ctrl_modifier

##
# Bash git prompt
if [ ! -d $HOME/.bash-git-prompt ]; then
    git clone https://github.com/magicmonty/bash-git-prompt.git ~/.bash-git-prompt --depth=1
fi
source $HOME/.bash-git-prompt/gitprompt.sh
GIT_PROMPT_ONLY_IN_REPO=1
GIT_PROMPT_FETCH_REMOTE_STATUS=0
GIT_PROMPT_START=" \[\033[01;39m\]\W\[\033[0m\]"
GIT_PROMPT_END=" ➤ "
